= Operator Commands
:toc:

== /oper

Authenticate as a server operator.

== /kill

Kill a client connection to the server.

== /kline

Ban a client from the server.

Specify "on" to set bans on remote servers.

This command is intended for Charybdis/Solanum servers.
Refer to your IRCd's documentation before using it.

See also: unkline

== /dline

Ban an IP address from the server.

Specify "on" to set bans on remote servers.

This command is intended for Charybdis/Solanum servers.
Refer to your IRCd's documentation before using it.

See also: undline

== /xline

Ban a gecos from the server.

Specify "on" to set bans on remote servers.

This command is intended for Charybdis/Solanum servers.
Refer to your IRCd's documentation before using it.

See also: unxline

== /resv

Ban a channel or nickname from the server.

Specify "on" to set bans on remote servers.

This command is intended for Charybdis/Solanum servers.
Refer to your IRCd's documentation before using it.

See also: unresv

== /unkline

Unban a client from the server.

See also: kline

== /undline

Unban an IP address from the server.

See also: dline

== /unxline

Unban a gecos from the server.

See also: xline

== /unresv

Unban a channel or nickname from the server.

See also: resv

== /testline

Check matching I/K/D lines for a `[[nick!]user@]host`.

== /testkline

Check matching K/D lines for a `[user@]host`.

== /testgecos

Check matching X lines for a `gecos`.

== /testmask

Test how many local and global clients match a mask.

== /masktrace

Outputs a list of local users matching the given masks.

== /chantrace

Outputs a list of channel members in etrace format.

== /trace

Outputs a list of users on a server.

See also: etrace

== /etrace

Outputs a list of users on a server,
including the contents of the USER messages they sent during registration.

See also: trace

== /map

Display network map.

== /sconnect

Connect two servers together.

== /squit

Split a server away from your side of the network.

== /modload

Load an IRCd module.

== /modunload

Unload an IRCd module.

== /modlist

List loaded IRCd modules.

== /modrestart

Reload all IRCd modules.

== /modreload

Reload an IRCd module.

== /grant

Manually assign a privset to a user.

== /privs

Check operator privileges of the target.
