= Channel Management Commands
:toc:

== /op

Grant channel operator privileges to yourself or another user.

Sends an OP command to ChanServ if you are not opped and
the current channel is in your configured `chanserv-channels`.

== /deop

Remove channel operator privileges from yourself or another user.

Sends a DEOP command to ChanServ if you are not opped and
the current channel is in your configured `chanserv-channels`.

== /voice

Grant voice to yourself or another user.

Sends a VOICE command to ChanServ if you are not opped and
the current channel is in your configured `chanserv-channels`.

== /devoice

Remove voice from yourself or another user.

Sends a DEVOICE command to ChanServ if you are not opped and
the current channel is in your configured `chanserv-channels`.

== /invite

Invite a user to the current channel.

Can acquire operator status from ChanServ if the current channel is in
your configured `chanserv-channels`.

== /kick

Kick a user from the current channel.

Can acquire operator status from ChanServ if the current channel is in
your configured `chanserv-channels`.

See also: kickban, remove

== /kickban

Ban and kick a user from the current channel.

Users are banned by hostname match.

Can acquire operator status from ChanServ if the current channel is in
your configured `chanserv-channels`.

See also: kick, remove

== /masks

Show the values of list modes (e.g. bans) for current channel.

Sends a `+MODE+` query to the server.
The result is cached if and only if you are in the current channel.

The `mode` argument is typically one of the following:

`b`: bans +
`i`: invite exemptions (op view only) +
`e`: ban exemptions (op view only) +
`q`: quiets (on Charybdis/Solanum-based networks)

== /mode

Set IRC modes.

When executed in a channel window, mode changes are applied to the channel.
When executed in a network window, mode changes are applied to your user.

This command has parameter sensitive tab-completion.

Can acquire operator status from ChanServ if the current channel is in
your configured `chanserv-channels`.

See also: masks, channelinfo

=== Examples

`+/mode -t+`               - Remove the topic lock +
`+/mode +b *!*@hostname+`  - Set a ban +
`+/mode -q *!*@hostname+`  - Remove a quiet +
`+/mode +vv user1 user2+`  - Voice two users +
`+/mode +v-o user1 user1+` - Demote an op to voice

== /quiet

Quiet a user, preventing them from speaking unless voiced.

This command only works on networks that have
channel mode `q` as a list mode (e.g. Charybdis/Solanum-based networks).
Some networks implement this functionality as an extban,
which is not supported by this command.

Can acquire operator status from ChanServ if the current channel is in
your configured `chanserv-channels`.

== /remove

Remove a user from the current channel.

Remove works like /kick except it results in a PART.

Not all servers support removal in this manner.
Refer to your server/network's documentation.

Can acquire operator status from ChanServ if the current channel is in
your configured `chanserv-channels`.

See also: kick, kickban

== /topic

View or set the topic of the current channel.

Tab-completion with no `message` specified will load the current topic.
