{-# Language QuasiQuotes, OverloadedStrings #-}
{-|
Module      : Digraphs
Description : Character mnemonics
Copyright   : (c) Eric Mertens, 2016
License     : ISC
Maintainer  : emertens@gmail.com

This module provides an implementation of /digraphs/ as implemented
in Vim and as specified in RFC 1345 (2-character only).

<https://tools.ietf.org/html/rfc1345>
<http://vimdoc.sourceforge.net/htmldoc/digraph.html>

-}
module Digraphs
  ( lookupDigraph
  , digraphs
  ) where

import           DigraphQuote
import           Data.List
import           Data.Text (Text)
import qualified Data.Text as Text

-- | Look up 2-character digraph.
lookupDigraph :: Char -> Char -> Maybe Char
lookupDigraph x y = fmap Text.last (find p (Text.chunksOf 3 digraphs))
  where
    p entry = Text.index entry 0 == x && Text.index entry 1 == y

------------------------------------------------------------------------

-- These are explicitly prohibited by the IRC RFC
--  NU 00  -- NULL (NUL)
--  LF 0a  -- LINE FEED (LF)
--  CR 0d  -- CARRIAGE RETURN (CR)

digraphs :: Text
digraphs = [digraphTable|
  SH   01    -- START OF HEADING (SOH)
  SX   02    -- START OF TEXT (STX)
  EX   03    -- END OF TEXT (ETX)
  ET   04    -- END OF TRANSMISSION (EOT)
  EQ   05    -- ENQUIRY (ENQ)
  AK   06    -- ACKNOWLEDGE (ACK)
  BL   07    -- BELL (BEL)
  BS   08    -- BACKSPACE (BS)
  HT   09    -- CHARACTER TABULATION (HT)
  VT   0b    -- LINE TABULATION (VT)
  FF   0c    -- FORM FEED (FF)
  SO   0e    -- SHIFT OUT (SO)
  SI   0f    -- SHIFT IN (SI)
  DL   10    -- DATALINK ESCAPE (DLE)
  D1   11    -- DEVICE CONTROL ONE (DC1)
  D2   12    -- DEVICE CONTROL TWO (DC2)
  D3   13    -- DEVICE CONTROL THREE (DC3)
  D4   14    -- DEVICE CONTROL FOUR (DC4)
  NK   15    -- NEGATIVE ACKNOWLEDGE (NAK)
  SY   16    -- SYNCHRONOUS IDLE (SYN)
  EB   17    -- END OF TRANSMISSION BLOCK (ETB)
  CN   18    -- CANCEL (CAN)
  EM   19    -- END OF MEDIUM (EM)
  SB   1a    -- SUBSTITUTE (SUB)
  EC   1b    -- ESCAPE (ESC)
  FS   1c    -- FILE SEPARATOR (IS4)
  GS   1d    -- GROUP SEPARATOR (IS3)
  RS   1e    -- RECORD SEPARATOR (IS2)
  US   1f    -- UNIT SEPARATOR (IS1)
  SP   20    -- SPACE
  Nb   23    -- NUMBER SIGN
  DO   24    -- DOLLAR SIGN
  At   40    -- COMMERCIAL AT
  <(   5b    -- LEFT SQUARE BRACKET
  //   5c    -- REVERSE SOLIDUS
  )>   5d    -- RIGHT SQUARE BRACKET
  '>   5e    -- CIRCUMFLEX ACCENT
  '!   60    -- GRAVE ACCENT
  (!   7b    -- LEFT CURLY BRACKET
  !!   7c    -- VERTICAL LINE
  !)   7d    -- RIGHT CURLY BRACKET
  '?   7e    -- TILDE
  DT   7f    -- DELETE (DEL)
  PA   80    -- PADDING CHARACTER (PAD)
  HO   81    -- HIGH OCTET PRESET (HOP)
  BH   82    -- BREAK PERMITTED HERE (BPH)
  NH   83    -- NO BREAK HERE (NBH)
  IN   84    -- INDEX (IND)
  NL   85    -- NEXT LINE (NEL)
  SA   86    -- START OF SELECTED AREA (SSA)
  ES   87    -- END OF SELECTED AREA (ESA)
  HS   88    -- CHARACTER TABULATION SET (HTS)
  HJ   89    -- CHARACTER TABULATION WITH JUSTIFICATION (HTJ)
  VS   8a    -- LINE TABULATION SET (VTS)
  PD   8b    -- PARTIAL LINE FORWARD (PLD)
  PU   8c    -- PARTIAL LINE BACKWARD (PLU)
  RI   8d    -- REVERSE LINE FEED (RI)
  S2   8e    -- SINGLE-SHIFT TWO (SS2)
  S3   8f    -- SINGLE-SHIFT THREE (SS3)
  DC   90    -- DEVICE CONTROL STRING (DCS)
  P1   91    -- PRIVATE USE ONE (PU1)
  P2   92    -- PRIVATE USE TWO (PU2)
  TS   93    -- SET TRANSMIT STATE (STS)
  CC   94    -- CANCEL CHARACTER (CCH)
  MW   95    -- MESSAGE WAITING (MW)
  SG   96    -- START OF GUARDED AREA (SPA)
  EG   97    -- END OF GUARDED AREA (EPA)
  SS   98    -- START OF STRING (SOS)
  GC   99    -- SINGLE GRAPHIC CHARACTER INTRODUCER (SGCI)
  SC   9a    -- SINGLE CHARACTER INTRODUCER (SCI)
  CI   9b    -- CONTROL SEQUENCE INTRODUCER (CSI)
  ST   9c    -- STRING TERMINATOR (ST)
  OC   9d    -- OPERATING SYSTEM COMMAND (OSC)
  PM   9e    -- PRIVACY MESSAGE (PM)
  AC   9f    -- APPLICATION PROGRAM COMMAND (APC)
  NS   a0    -- NO-BREAK SPACE
  !I   a1    -- INVERTED EXCLAMATION MARK
  Ct   a2    -- CENT SIGN
  Pd   a3    -- POUND SIGN
  Cu   a4    -- CURRENCY SIGN
  Ye   a5    -- YEN SIGN
  BB   a6    -- BROKEN BAR
  SE   a7    -- SECTION SIGN
  ':   a8    -- DIAERESIS
  Co   a9    -- COPYRIGHT SIGN
  -a   aa    -- FEMININE ORDINAL INDICATOR
  <<   ab    -- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
  NO   ac    -- NOT SIGN
  --   ad    -- SOFT HYPHEN
  Rg   ae    -- REGISTERED SIGN
  'm   af    -- MACRON
  DG   b0    -- DEGREE SIGN
  +-   b1    -- PLUS-MINUS SIGN
  2S   b2    -- SUPERSCRIPT TWO
  3S   b3    -- SUPERSCRIPT THREE
  ''   b4    -- ACUTE ACCENT
  My   b5    -- MICRO SIGN
  PI   b6    -- PILCROW SIGN
  .M   b7    -- MIDDLE DOT
  ',   b8    -- CEDILLA
  1S   b9    -- SUPERSCRIPT ONE
  -o   ba    -- MASCULINE ORDINAL INDICATOR
  >>   bb    -- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
  14   bc    -- VULGAR FRACTION ONE QUARTER
  12   bd    -- VULGAR FRACTION ONE HALF
  34   be    -- VULGAR FRACTION THREE QUARTERS
  ?I   bf    -- INVERTED QUESTION MARK
  A!   c0    -- LATIN CAPITAL LETTER A WITH GRAVE
  A'   c1    -- LATIN CAPITAL LETTER A WITH ACUTE
  A>   c2    -- LATIN CAPITAL LETTER A WITH CIRCUMFLEX
  A?   c3    -- LATIN CAPITAL LETTER A WITH TILDE
  A:   c4    -- LATIN CAPITAL LETTER A WITH DIAERESIS
  AA   c5    -- LATIN CAPITAL LETTER A WITH RING ABOVE
  AE   c6    -- LATIN CAPITAL LETTER AE
  C,   c7    -- LATIN CAPITAL LETTER C WITH CEDILLA
  E!   c8    -- LATIN CAPITAL LETTER E WITH GRAVE
  E'   c9    -- LATIN CAPITAL LETTER E WITH ACUTE
  E>   ca    -- LATIN CAPITAL LETTER E WITH CIRCUMFLEX
  E:   cb    -- LATIN CAPITAL LETTER E WITH DIAERESIS
  I!   cc    -- LATIN CAPITAL LETTER I WITH GRAVE
  I'   cd    -- LATIN CAPITAL LETTER I WITH ACUTE
  I>   ce    -- LATIN CAPITAL LETTER I WITH CIRCUMFLEX
  I:   cf    -- LATIN CAPITAL LETTER I WITH DIAERESIS
  D-   d0    -- LATIN CAPITAL LETTER ETH (Icelandic)
  N?   d1    -- LATIN CAPITAL LETTER N WITH TILDE
  O!   d2    -- LATIN CAPITAL LETTER O WITH GRAVE
  O'   d3    -- LATIN CAPITAL LETTER O WITH ACUTE
  O>   d4    -- LATIN CAPITAL LETTER O WITH CIRCUMFLEX
  O?   d5    -- LATIN CAPITAL LETTER O WITH TILDE
  O:   d6    -- LATIN CAPITAL LETTER O WITH DIAERESIS
  *X   d7    -- MULTIPLICATION SIGN
  O/   d8    -- LATIN CAPITAL LETTER O WITH STROKE
  U!   d9    -- LATIN CAPITAL LETTER U WITH GRAVE
  U'   da    -- LATIN CAPITAL LETTER U WITH ACUTE
  U>   db    -- LATIN CAPITAL LETTER U WITH CIRCUMFLEX
  U:   dc    -- LATIN CAPITAL LETTER U WITH DIAERESIS
  Y'   dd    -- LATIN CAPITAL LETTER Y WITH ACUTE
  TH   de    -- LATIN CAPITAL LETTER THORN (Icelandic)
  ss   df    -- LATIN SMALL LETTER SHARP S (German)
  a!   e0    -- LATIN SMALL LETTER A WITH GRAVE
  a'   e1    -- LATIN SMALL LETTER A WITH ACUTE
  a>   e2    -- LATIN SMALL LETTER A WITH CIRCUMFLEX
  a?   e3    -- LATIN SMALL LETTER A WITH TILDE
  a:   e4    -- LATIN SMALL LETTER A WITH DIAERESIS
  aa   e5    -- LATIN SMALL LETTER A WITH RING ABOVE
  ae   e6    -- LATIN SMALL LETTER AE
  c,   e7    -- LATIN SMALL LETTER C WITH CEDILLA
  e!   e8    -- LATIN SMALL LETTER E WITH GRAVE
  e'   e9    -- LATIN SMALL LETTER E WITH ACUTE
  e>   ea    -- LATIN SMALL LETTER E WITH CIRCUMFLEX
  e:   eb    -- LATIN SMALL LETTER E WITH DIAERESIS
  i!   ec    -- LATIN SMALL LETTER I WITH GRAVE
  i'   ed    -- LATIN SMALL LETTER I WITH ACUTE
  i>   ee    -- LATIN SMALL LETTER I WITH CIRCUMFLEX
  i:   ef    -- LATIN SMALL LETTER I WITH DIAERESIS
  d-   f0    -- LATIN SMALL LETTER ETH (Icelandic)
  n?   f1    -- LATIN SMALL LETTER N WITH TILDE
  o!   f2    -- LATIN SMALL LETTER O WITH GRAVE
  o'   f3    -- LATIN SMALL LETTER O WITH ACUTE
  o>   f4    -- LATIN SMALL LETTER O WITH CIRCUMFLEX
  o?   f5    -- LATIN SMALL LETTER O WITH TILDE
  o:   f6    -- LATIN SMALL LETTER O WITH DIAERESIS
  -:   f7    -- DIVISION SIGN
  o/   f8    -- LATIN SMALL LETTER O WITH STROKE
  u!   f9    -- LATIN SMALL LETTER U WITH GRAVE
  u'   fa    -- LATIN SMALL LETTER U WITH ACUTE
  u>   fb    -- LATIN SMALL LETTER U WITH CIRCUMFLEX
  u:   fc    -- LATIN SMALL LETTER U WITH DIAERESIS
  y'   fd    -- LATIN SMALL LETTER Y WITH ACUTE
  th   fe    -- LATIN SMALL LETTER THORN (Icelandic)
  y:   ff    -- LATIN SMALL LETTER Y WITH DIAERESIS
  A- 0100    -- LATIN CAPITAL LETTER A WITH MACRON
  a- 0101    -- LATIN SMALL LETTER A WITH MACRON
  A( 0102    -- LATIN CAPITAL LETTER A WITH BREVE
  a( 0103    -- LATIN SMALL LETTER A WITH BREVE
  A; 0104    -- LATIN CAPITAL LETTER A WITH OGONEK
  a; 0105    -- LATIN SMALL LETTER A WITH OGONEK
  C' 0106    -- LATIN CAPITAL LETTER C WITH ACUTE
  c' 0107    -- LATIN SMALL LETTER C WITH ACUTE
  C> 0108    -- LATIN CAPITAL LETTER C WITH CIRCUMFLEX
  c> 0109    -- LATIN SMALL LETTER C WITH CIRCUMFLEX
  C. 010A    -- LATIN CAPITAL LETTER C WITH DOT ABOVE
  c. 010B    -- LATIN SMALL LETTER C WITH DOT ABOVE
  C< 010C    -- LATIN CAPITAL LETTER C WITH CARON
  c< 010D    -- LATIN SMALL LETTER C WITH CARON
  D< 010E    -- LATIN CAPITAL LETTER D WITH CARON
  d< 010F    -- LATIN SMALL LETTER D WITH CARON
  D/ 0110    -- LATIN CAPITAL LETTER D WITH STROKE
  d/ 0111    -- LATIN SMALL LETTER D WITH STROKE
  E- 0112    -- LATIN CAPITAL LETTER E WITH MACRON
  e- 0113    -- LATIN SMALL LETTER E WITH MACRON
  E( 0114    -- LATIN CAPITAL LETTER E WITH BREVE
  e( 0115    -- LATIN SMALL LETTER E WITH BREVE
  E. 0116    -- LATIN CAPITAL LETTER E WITH DOT ABOVE
  e. 0117    -- LATIN SMALL LETTER E WITH DOT ABOVE
  E; 0118    -- LATIN CAPITAL LETTER E WITH OGONEK
  e; 0119    -- LATIN SMALL LETTER E WITH OGONEK
  E< 011A    -- LATIN CAPITAL LETTER E WITH CARON
  e< 011B    -- LATIN SMALL LETTER E WITH CARON
  G> 011C    -- LATIN CAPITAL LETTER G WITH CIRCUMFLEX
  g> 011D    -- LATIN SMALL LETTER G WITH CIRCUMFLEX
  G( 011E    -- LATIN CAPITAL LETTER G WITH BREVE
  g( 011F    -- LATIN SMALL LETTER G WITH BREVE
  G. 0120    -- LATIN CAPITAL LETTER G WITH DOT ABOVE
  g. 0121    -- LATIN SMALL LETTER G WITH DOT ABOVE
  G, 0122    -- LATIN CAPITAL LETTER G WITH CEDILLA
  g, 0123    -- LATIN SMALL LETTER G WITH CEDILLA
  H> 0124    -- LATIN CAPITAL LETTER H WITH CIRCUMFLEX
  h> 0125    -- LATIN SMALL LETTER H WITH CIRCUMFLEX
  H/ 0126    -- LATIN CAPITAL LETTER H WITH STROKE
  h/ 0127    -- LATIN SMALL LETTER H WITH STROKE
  I? 0128    -- LATIN CAPITAL LETTER I WITH TILDE
  i? 0129    -- LATIN SMALL LETTER I WITH TILDE
  I- 012A    -- LATIN CAPITAL LETTER I WITH MACRON
  i- 012B    -- LATIN SMALL LETTER I WITH MACRON
  I( 012C    -- LATIN CAPITAL LETTER I WITH BREVE
  i( 012D    -- LATIN SMALL LETTER I WITH BREVE
  I; 012E    -- LATIN CAPITAL LETTER I WITH OGONEK
  i; 012F    -- LATIN SMALL LETTER I WITH OGONEK
  I. 0130    -- LATIN CAPITAL LETTER I WITH DOT ABOVE
  i. 0131    -- LATIN SMALL LETTER DOTLESS I
  IJ 0132    -- LATIN CAPITAL LIGATURE IJ
  ij 0133    -- LATIN SMALL LIGATURE IJ
  J> 0134    -- LATIN CAPITAL LETTER J WITH CIRCUMFLEX
  j> 0135    -- LATIN SMALL LETTER J WITH CIRCUMFLEX
  K, 0136    -- LATIN CAPITAL LETTER K WITH CEDILLA
  k, 0137    -- LATIN SMALL LETTER K WITH CEDILLA
  kk 0138    -- LATIN SMALL LETTER KRA
  L' 0139    -- LATIN CAPITAL LETTER L WITH ACUTE
  l' 013A    -- LATIN SMALL LETTER L WITH ACUTE
  L, 013B    -- LATIN CAPITAL LETTER L WITH CEDILLA
  l, 013C    -- LATIN SMALL LETTER L WITH CEDILLA
  L< 013D    -- LATIN CAPITAL LETTER L WITH CARON
  l< 013E    -- LATIN SMALL LETTER L WITH CARON
  L. 013F    -- LATIN CAPITAL LETTER L WITH MIDDLE DOT
  l. 0140    -- LATIN SMALL LETTER L WITH MIDDLE DOT
  L/ 0141    -- LATIN CAPITAL LETTER L WITH STROKE
  l/ 0142    -- LATIN SMALL LETTER L WITH STROKE
  N' 0143    -- LATIN CAPITAL LETTER N WITH ACUTE `
  n' 0144    -- LATIN SMALL LETTER N WITH ACUTE `
  N, 0145    -- LATIN CAPITAL LETTER N WITH CEDILLA `
  n, 0146    -- LATIN SMALL LETTER N WITH CEDILLA `
  N< 0147    -- LATIN CAPITAL LETTER N WITH CARON `
  n< 0148    -- LATIN SMALL LETTER N WITH CARON `
  'n 0149    -- LATIN SMALL LETTER N PRECEDED BY APOSTROPHE `
  NG 014A    -- LATIN CAPITAL LETTER ENG
  ng 014B    -- LATIN SMALL LETTER ENG
  O- 014C    -- LATIN CAPITAL LETTER O WITH MACRON
  o- 014D    -- LATIN SMALL LETTER O WITH MACRON
  O( 014E    -- LATIN CAPITAL LETTER O WITH BREVE
  o( 014F    -- LATIN SMALL LETTER O WITH BREVE
  O" 0150    -- LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
  o" 0151    -- LATIN SMALL LETTER O WITH DOUBLE ACUTE
  OE 0152    -- LATIN CAPITAL LIGATURE OE
  oe 0153    -- LATIN SMALL LIGATURE OE
  R' 0154    -- LATIN CAPITAL LETTER R WITH ACUTE
  r' 0155    -- LATIN SMALL LETTER R WITH ACUTE
  R, 0156    -- LATIN CAPITAL LETTER R WITH CEDILLA
  r, 0157    -- LATIN SMALL LETTER R WITH CEDILLA
  R< 0158    -- LATIN CAPITAL LETTER R WITH CARON
  r< 0159    -- LATIN SMALL LETTER R WITH CARON
  S' 015A    -- LATIN CAPITAL LETTER S WITH ACUTE
  s' 015B    -- LATIN SMALL LETTER S WITH ACUTE
  S> 015C    -- LATIN CAPITAL LETTER S WITH CIRCUMFLEX
  s> 015D    -- LATIN SMALL LETTER S WITH CIRCUMFLEX
  S, 015E    -- LATIN CAPITAL LETTER S WITH CEDILLA
  s, 015F    -- LATIN SMALL LETTER S WITH CEDILLA
  S< 0160    -- LATIN CAPITAL LETTER S WITH CARON
  s< 0161    -- LATIN SMALL LETTER S WITH CARON
  T, 0162    -- LATIN CAPITAL LETTER T WITH CEDILLA
  t, 0163    -- LATIN SMALL LETTER T WITH CEDILLA
  T< 0164    -- LATIN CAPITAL LETTER T WITH CARON
  t< 0165    -- LATIN SMALL LETTER T WITH CARON
  T/ 0166    -- LATIN CAPITAL LETTER T WITH STROKE
  t/ 0167    -- LATIN SMALL LETTER T WITH STROKE
  U? 0168    -- LATIN CAPITAL LETTER U WITH TILDE
  u? 0169    -- LATIN SMALL LETTER U WITH TILDE
  U- 016A    -- LATIN CAPITAL LETTER U WITH MACRON
  u- 016B    -- LATIN SMALL LETTER U WITH MACRON
  U( 016C    -- LATIN CAPITAL LETTER U WITH BREVE
  u( 016D    -- LATIN SMALL LETTER U WITH BREVE
  U0 016E    -- LATIN CAPITAL LETTER U WITH RING ABOVE
  u0 016F    -- LATIN SMALL LETTER U WITH RING ABOVE
  U" 0170    -- LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
  u" 0171    -- LATIN SMALL LETTER U WITH DOUBLE ACUTE
  U; 0172    -- LATIN CAPITAL LETTER U WITH OGONEK
  u; 0173    -- LATIN SMALL LETTER U WITH OGONEK
  W> 0174    -- LATIN CAPITAL LETTER W WITH CIRCUMFLEX
  w> 0175    -- LATIN SMALL LETTER W WITH CIRCUMFLEX
  Y> 0176    -- LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
  y> 0177    -- LATIN SMALL LETTER Y WITH CIRCUMFLEX
  Y: 0178    -- LATIN CAPITAL LETTER Y WITH DIAERESIS
  Z' 0179    -- LATIN CAPITAL LETTER Z WITH ACUTE
  z' 017A    -- LATIN SMALL LETTER Z WITH ACUTE
  Z. 017B    -- LATIN CAPITAL LETTER Z WITH DOT ABOVE
  z. 017C    -- LATIN SMALL LETTER Z WITH DOT ABOVE
  Z< 017D    -- LATIN CAPITAL LETTER Z WITH CARON
  z< 017E    -- LATIN SMALL LETTER Z WITH CARON
  O9 01A0    -- LATIN CAPITAL LETTER O WITH HORN
  o9 01A1    -- LATIN SMALL LETTER O WITH HORN
  OI 01A2    -- LATIN CAPITAL LETTER OI
  oi 01A3    -- LATIN SMALL LETTER OI
  yr 01A6    -- LATIN LETTER YR
  U9 01AF    -- LATIN CAPITAL LETTER U WITH HORN
  u9 01B0    -- LATIN SMALL LETTER U WITH HORN
  Z/ 01B5    -- LATIN CAPITAL LETTER Z WITH STROKE
  z/ 01B6    -- LATIN SMALL LETTER Z WITH STROKE
  ED 01B7    -- LATIN CAPITAL LETTER EZH
  A< 01CD    -- LATIN CAPITAL LETTER A WITH CARON
  a< 01CE    -- LATIN SMALL LETTER A WITH CARON
  I< 01CF    -- LATIN CAPITAL LETTER I WITH CARON
  i< 01D0    -- LATIN SMALL LETTER I WITH CARON
  O< 01D1    -- LATIN CAPITAL LETTER O WITH CARON
  o< 01D2    -- LATIN SMALL LETTER O WITH CARON
  U< 01D3    -- LATIN CAPITAL LETTER U WITH CARON
  u< 01D4    -- LATIN SMALL LETTER U WITH CARON
  A1 01DE    -- LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
  a1 01DF    -- LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
  A7 01E0    -- LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
  a7 01E1    -- LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
  A3 01E2    -- LATIN CAPITAL LETTER AE WITH MACRON
  a3 01E3    -- LATIN SMALL LETTER AE WITH MACRON
  G/ 01E4    -- LATIN CAPITAL LETTER G WITH STROKE
  g/ 01E5    -- LATIN SMALL LETTER G WITH STROKE
  G< 01E6    -- LATIN CAPITAL LETTER G WITH CARON
  g< 01E7    -- LATIN SMALL LETTER G WITH CARON
  K< 01E8    -- LATIN CAPITAL LETTER K WITH CARON
  k< 01E9    -- LATIN SMALL LETTER K WITH CARON
  O; 01EA    -- LATIN CAPITAL LETTER O WITH OGONEK
  o; 01EB    -- LATIN SMALL LETTER O WITH OGONEK
  O1 01EC    -- LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
  o1 01ED    -- LATIN SMALL LETTER O WITH OGONEK AND MACRON
  EZ 01EE    -- LATIN CAPITAL LETTER EZH WITH CARON
  ez 01EF    -- LATIN SMALL LETTER EZH WITH CARON
  j< 01F0    -- LATIN SMALL LETTER J WITH CARON
  G' 01F4    -- LATIN CAPITAL LETTER G WITH ACUTE
  g' 01F5    -- LATIN SMALL LETTER G WITH ACUTE
  ;S 02BF    -- MODIFIER LETTER LEFT HALF RING
  '< 02C7    -- CARON
  '( 02D8    -- BREVE
  '. 02D9    -- DOT ABOVE
  '0 02DA    -- RING ABOVE
  '; 02DB    -- OGONEK
  '" 02DD    -- DOUBLE ACUTE ACCENT
  A% 0386    -- GREEK CAPITAL LETTER ALPHA WITH TONOS
  E% 0388    -- GREEK CAPITAL LETTER EPSILON WITH TONOS
  Y% 0389    -- GREEK CAPITAL LETTER ETA WITH TONOS
  I% 038A    -- GREEK CAPITAL LETTER IOTA WITH TONOS
  O% 038C    -- GREEK CAPITAL LETTER OMICRON WITH TONOS
  U% 038E    -- GREEK CAPITAL LETTER UPSILON WITH TONOS
  W% 038F    -- GREEK CAPITAL LETTER OMEGA WITH TONOS
  i3 0390    -- GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
  A* 0391    -- GREEK CAPITAL LETTER ALPHA
  B* 0392    -- GREEK CAPITAL LETTER BETA
  G* 0393    -- GREEK CAPITAL LETTER GAMMA
  D* 0394    -- GREEK CAPITAL LETTER DELTA
  E* 0395    -- GREEK CAPITAL LETTER EPSILON
  Z* 0396    -- GREEK CAPITAL LETTER ZETA
  Y* 0397    -- GREEK CAPITAL LETTER ETA
  H* 0398    -- GREEK CAPITAL LETTER THETA
  I* 0399    -- GREEK CAPITAL LETTER IOTA
  K* 039A    -- GREEK CAPITAL LETTER KAPPA
  L* 039B    -- GREEK CAPITAL LETTER LAMDA
  M* 039C    -- GREEK CAPITAL LETTER MU
  N* 039D    -- GREEK CAPITAL LETTER NU
  C* 039E    -- GREEK CAPITAL LETTER XI
  O* 039F    -- GREEK CAPITAL LETTER OMICRON
  P* 03A0    -- GREEK CAPITAL LETTER PI
  R* 03A1    -- GREEK CAPITAL LETTER RHO
  S* 03A3    -- GREEK CAPITAL LETTER SIGMA
  T* 03A4    -- GREEK CAPITAL LETTER TAU
  U* 03A5    -- GREEK CAPITAL LETTER UPSILON
  F* 03A6    -- GREEK CAPITAL LETTER PHI
  X* 03A7    -- GREEK CAPITAL LETTER CHI
  Q* 03A8    -- GREEK CAPITAL LETTER PSI
  W* 03A9    -- GREEK CAPITAL LETTER OMEGA
  J* 03AA    -- GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
  V* 03AB    -- GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
  a% 03AC    -- GREEK SMALL LETTER ALPHA WITH TONOS
  e% 03AD    -- GREEK SMALL LETTER EPSILON WITH TONOS
  y% 03AE    -- GREEK SMALL LETTER ETA WITH TONOS
  i% 03AF    -- GREEK SMALL LETTER IOTA WITH TONOS
  u3 03B0    -- GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
  a* 03B1    -- GREEK SMALL LETTER ALPHA
  b* 03B2    -- GREEK SMALL LETTER BETA
  g* 03B3    -- GREEK SMALL LETTER GAMMA
  d* 03B4    -- GREEK SMALL LETTER DELTA
  e* 03B5    -- GREEK SMALL LETTER EPSILON
  z* 03B6    -- GREEK SMALL LETTER ZETA
  y* 03B7    -- GREEK SMALL LETTER ETA
  h* 03B8    -- GREEK SMALL LETTER THETA
  i* 03B9    -- GREEK SMALL LETTER IOTA
  k* 03BA    -- GREEK SMALL LETTER KAPPA
  l* 03BB    -- GREEK SMALL LETTER LAMDA
  m* 03BC    -- GREEK SMALL LETTER MU
  n* 03BD    -- GREEK SMALL LETTER NU
  c* 03BE    -- GREEK SMALL LETTER XI
  o* 03BF    -- GREEK SMALL LETTER OMICRON
  p* 03C0    -- GREEK SMALL LETTER PI
  r* 03C1    -- GREEK SMALL LETTER RHO
  *s 03C2    -- GREEK SMALL LETTER FINAL SIGMA
  s* 03C3    -- GREEK SMALL LETTER SIGMA
  t* 03C4    -- GREEK SMALL LETTER TAU
  u* 03C5    -- GREEK SMALL LETTER UPSILON
  f* 03C6    -- GREEK SMALL LETTER PHI
  x* 03C7    -- GREEK SMALL LETTER CHI
  q* 03C8    -- GREEK SMALL LETTER PSI
  w* 03C9    -- GREEK SMALL LETTER OMEGA
  j* 03CA    -- GREEK SMALL LETTER IOTA WITH DIALYTIKA
  v* 03CB    -- GREEK SMALL LETTER UPSILON WITH DIALYTIKA
  o% 03CC    -- GREEK SMALL LETTER OMICRON WITH TONOS
  u% 03CD    -- GREEK SMALL LETTER UPSILON WITH TONOS
  w% 03CE    -- GREEK SMALL LETTER OMEGA WITH TONOS
  'G 03D8    -- GREEK LETTER ARCHAIC KOPPA
  ,G 03D9    -- GREEK SMALL LETTER ARCHAIC KOPPA
  T3 03DA    -- GREEK LETTER STIGMA
  t3 03DB    -- GREEK SMALL LETTER STIGMA
  M3 03DC    -- GREEK LETTER DIGAMMA
  m3 03DD    -- GREEK SMALL LETTER DIGAMMA
  K3 03DE    -- GREEK LETTER KOPPA
  k3 03DF    -- GREEK SMALL LETTER KOPPA
  P3 03E0    -- GREEK LETTER SAMPI
  p3 03E1    -- GREEK SMALL LETTER SAMPI
  '% 03F4    -- GREEK CAPITAL THETA SYMBOL
  j3 03F5    -- GREEK LUNATE EPSILON SYMBOL
  IO 0401    -- CYRILLIC CAPITAL LETTER IO
  D% 0402    -- CYRILLIC CAPITAL LETTER DJE
  G% 0403    -- CYRILLIC CAPITAL LETTER GJE
  IE 0404    -- CYRILLIC CAPITAL LETTER UKRAINIAN IE
  DS 0405    -- CYRILLIC CAPITAL LETTER DZE
  II 0406    -- CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
  YI 0407    -- CYRILLIC CAPITAL LETTER YI
  J% 0408    -- CYRILLIC CAPITAL LETTER JE
  LJ 0409    -- CYRILLIC CAPITAL LETTER LJE
  NJ 040A    -- CYRILLIC CAPITAL LETTER NJE
  Ts 040B    -- CYRILLIC CAPITAL LETTER TSHE
  KJ 040C    -- CYRILLIC CAPITAL LETTER KJE
  V% 040E    -- CYRILLIC CAPITAL LETTER SHORT U
  DZ 040F    -- CYRILLIC CAPITAL LETTER DZHE
  A= 0410    -- CYRILLIC CAPITAL LETTER A
  B= 0411    -- CYRILLIC CAPITAL LETTER BE
  V= 0412    -- CYRILLIC CAPITAL LETTER VE
  G= 0413    -- CYRILLIC CAPITAL LETTER GHE
  D= 0414    -- CYRILLIC CAPITAL LETTER DE
  E= 0415    -- CYRILLIC CAPITAL LETTER IE
  Z% 0416    -- CYRILLIC CAPITAL LETTER ZHE
  Z= 0417    -- CYRILLIC CAPITAL LETTER ZE
  I= 0418    -- CYRILLIC CAPITAL LETTER I
  J= 0419    -- CYRILLIC CAPITAL LETTER SHORT I
  K= 041A    -- CYRILLIC CAPITAL LETTER KA
  L= 041B    -- CYRILLIC CAPITAL LETTER EL
  M= 041C    -- CYRILLIC CAPITAL LETTER EM
  N= 041D    -- CYRILLIC CAPITAL LETTER EN
  O= 041E    -- CYRILLIC CAPITAL LETTER O
  P= 041F    -- CYRILLIC CAPITAL LETTER PE
  R= 0420    -- CYRILLIC CAPITAL LETTER ER
  S= 0421    -- CYRILLIC CAPITAL LETTER ES
  T= 0422    -- CYRILLIC CAPITAL LETTER TE
  U= 0423    -- CYRILLIC CAPITAL LETTER U
  F= 0424    -- CYRILLIC CAPITAL LETTER EF
  H= 0425    -- CYRILLIC CAPITAL LETTER HA
  C= 0426    -- CYRILLIC CAPITAL LETTER TSE
  C% 0427    -- CYRILLIC CAPITAL LETTER CHE
  S% 0428    -- CYRILLIC CAPITAL LETTER SHA
  Sc 0429    -- CYRILLIC CAPITAL LETTER SHCHA
  =' 042A    -- CYRILLIC CAPITAL LETTER HARD SIGN
  Y= 042B    -- CYRILLIC CAPITAL LETTER YERU
  %' 042C    -- CYRILLIC CAPITAL LETTER SOFT SIGN
  JE 042D    -- CYRILLIC CAPITAL LETTER E
  JU 042E    -- CYRILLIC CAPITAL LETTER YU
  JA 042F    -- CYRILLIC CAPITAL LETTER YA
  a= 0430    -- CYRILLIC SMALL LETTER A
  b= 0431    -- CYRILLIC SMALL LETTER BE
  v= 0432    -- CYRILLIC SMALL LETTER VE
  g= 0433    -- CYRILLIC SMALL LETTER GHE
  d= 0434    -- CYRILLIC SMALL LETTER DE
  e= 0435    -- CYRILLIC SMALL LETTER IE
  z% 0436    -- CYRILLIC SMALL LETTER ZHE
  z= 0437    -- CYRILLIC SMALL LETTER ZE
  i= 0438    -- CYRILLIC SMALL LETTER I
  j= 0439    -- CYRILLIC SMALL LETTER SHORT I
  k= 043A    -- CYRILLIC SMALL LETTER KA
  l= 043B    -- CYRILLIC SMALL LETTER EL
  m= 043C    -- CYRILLIC SMALL LETTER EM
  n= 043D    -- CYRILLIC SMALL LETTER EN
  o= 043E    -- CYRILLIC SMALL LETTER O
  p= 043F    -- CYRILLIC SMALL LETTER PE
  r= 0440    -- CYRILLIC SMALL LETTER ER
  s= 0441    -- CYRILLIC SMALL LETTER ES
  t= 0442    -- CYRILLIC SMALL LETTER TE
  u= 0443    -- CYRILLIC SMALL LETTER U
  f= 0444    -- CYRILLIC SMALL LETTER EF
  h= 0445    -- CYRILLIC SMALL LETTER HA
  c= 0446    -- CYRILLIC SMALL LETTER TSE
  c% 0447    -- CYRILLIC SMALL LETTER CHE
  s% 0448    -- CYRILLIC SMALL LETTER SHA
  sc 0449    -- CYRILLIC SMALL LETTER SHCHA
  =' 044A    -- CYRILLIC SMALL LETTER HARD SIGN
  y= 044B    -- CYRILLIC SMALL LETTER YERU
  %' 044C    -- CYRILLIC SMALL LETTER SOFT SIGN
  je 044D    -- CYRILLIC SMALL LETTER E
  ju 044E    -- CYRILLIC SMALL LETTER YU
  ja 044F    -- CYRILLIC SMALL LETTER YA
  io 0451    -- CYRILLIC SMALL LETTER IO
  d% 0452    -- CYRILLIC SMALL LETTER DJE
  g% 0453    -- CYRILLIC SMALL LETTER GJE
  ie 0454    -- CYRILLIC SMALL LETTER UKRAINIAN IE
  ds 0455    -- CYRILLIC SMALL LETTER DZE
  ii 0456    -- CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
  yi 0457    -- CYRILLIC SMALL LETTER YI
  j% 0458    -- CYRILLIC SMALL LETTER JE
  lj 0459    -- CYRILLIC SMALL LETTER LJE
  nj 045A    -- CYRILLIC SMALL LETTER NJE
  ts 045B    -- CYRILLIC SMALL LETTER TSHE
  kj 045C    -- CYRILLIC SMALL LETTER KJE
  v% 045E    -- CYRILLIC SMALL LETTER SHORT U
  dz 045F    -- CYRILLIC SMALL LETTER DZHE
  Y3 0462    -- CYRILLIC CAPITAL LETTER YAT
  y3 0463    -- CYRILLIC SMALL LETTER YAT
  O3 046A    -- CYRILLIC CAPITAL LETTER BIG YUS
  o3 046B    -- CYRILLIC SMALL LETTER BIG YUS
  F3 0472    -- CYRILLIC CAPITAL LETTER FITA
  f3 0473    -- CYRILLIC SMALL LETTER FITA
  V3 0474    -- CYRILLIC CAPITAL LETTER IZHITSA
  v3 0475    -- CYRILLIC SMALL LETTER IZHITSA
  C3 0480    -- CYRILLIC CAPITAL LETTER KOPPA
  c3 0481    -- CYRILLIC SMALL LETTER KOPPA
  G3 0490    -- CYRILLIC CAPITAL LETTER GHE WITH UPTURN
  g3 0491    -- CYRILLIC SMALL LETTER GHE WITH UPTURN
  A+ 05D0    -- HEBREW LETTER ALEF
  B+ 05D1    -- HEBREW LETTER BET
  G+ 05D2    -- HEBREW LETTER GIMEL
  D+ 05D3    -- HEBREW LETTER DALET
  H+ 05D4    -- HEBREW LETTER HE
  W+ 05D5    -- HEBREW LETTER VAV
  Z+ 05D6    -- HEBREW LETTER ZAYIN
  X+ 05D7    -- HEBREW LETTER HET
  Tj 05D8    -- HEBREW LETTER TET
  J+ 05D9    -- HEBREW LETTER YOD
  K% 05DA    -- HEBREW LETTER FINAL KAF
  K+ 05DB    -- HEBREW LETTER KAF
  L+ 05DC    -- HEBREW LETTER LAMED
  M% 05DD    -- HEBREW LETTER FINAL MEM
  M+ 05DE    -- HEBREW LETTER MEM
  N% 05DF    -- HEBREW LETTER FINAL NUN `
  N+ 05E0    -- HEBREW LETTER NUN `
  S+ 05E1    -- HEBREW LETTER SAMEKH
  E+ 05E2    -- HEBREW LETTER AYIN
  P% 05E3    -- HEBREW LETTER FINAL PE
  P+ 05E4    -- HEBREW LETTER PE
  Zj 05E5    -- HEBREW LETTER FINAL TSADI
  ZJ 05E6    -- HEBREW LETTER TSADI
  Q+ 05E7    -- HEBREW LETTER QOF
  R+ 05E8    -- HEBREW LETTER RESH
  Sh 05E9    -- HEBREW LETTER SHIN
  T+ 05EA    -- HEBREW LETTER TAV
  ,+ 060C    -- ARABIC COMMA
  ;+ 061B    -- ARABIC SEMICOLON
  ?+ 061F    -- ARABIC QUESTION MARK
  H' 0621    -- ARABIC LETTER HAMZA
  aM 0622    -- ARABIC LETTER ALEF WITH MADDA ABOVE
  aH 0623    -- ARABIC LETTER ALEF WITH HAMZA ABOVE
  wH 0624    -- ARABIC LETTER WAW WITH HAMZA ABOVE
  ah 0625    -- ARABIC LETTER ALEF WITH HAMZA BELOW
  yH 0626    -- ARABIC LETTER YEH WITH HAMZA ABOVE
  a+ 0627    -- ARABIC LETTER ALEF
  b+ 0628    -- ARABIC LETTER BEH
  tm 0629    -- ARABIC LETTER TEH MARBUTA
  t+ 062A    -- ARABIC LETTER TEH
  tk 062B    -- ARABIC LETTER THEH
  g+ 062C    -- ARABIC LETTER JEEM
  hk 062D    -- ARABIC LETTER HAH
  x+ 062E    -- ARABIC LETTER KHAH
  d+ 062F    -- ARABIC LETTER DAL
  dk 0630    -- ARABIC LETTER THAL
  r+ 0631    -- ARABIC LETTER REH
  z+ 0632    -- ARABIC LETTER ZAIN
  s+ 0633    -- ARABIC LETTER SEEN
  sn 0634    -- ARABIC LETTER SHEEN
  c+ 0635    -- ARABIC LETTER SAD
  dd 0636    -- ARABIC LETTER DAD
  tj 0637    -- ARABIC LETTER TAH
  zH 0638    -- ARABIC LETTER ZAH
  e+ 0639    -- ARABIC LETTER AIN
  i+ 063A    -- ARABIC LETTER GHAIN
  ++ 0640    -- ARABIC TATWEEL
  f+ 0641    -- ARABIC LETTER FEH
  q+ 0642    -- ARABIC LETTER QAF
  k+ 0643    -- ARABIC LETTER KAF
  l+ 0644    -- ARABIC LETTER LAM
  m+ 0645    -- ARABIC LETTER MEEM
  n+ 0646    -- ARABIC LETTER NOON
  h+ 0647    -- ARABIC LETTER HEH
  w+ 0648    -- ARABIC LETTER WAW
  j+ 0649    -- ARABIC LETTER ALEF MAKSURA
  y+ 064A    -- ARABIC LETTER YEH
  :+ 064B    -- ARABIC FATHATAN
  "+ 064C    -- ARABIC DAMMATAN
  =+ 064D    -- ARABIC KASRATAN
  /+ 064E    -- ARABIC FATHA
  '+ 064F    -- ARABIC DAMMA
  1+ 0650    -- ARABIC KASRA
  3+ 0651    -- ARABIC SHADDA
  0+ 0652    -- ARABIC SUKUN
  aS 0670    -- ARABIC LETTER SUPERSCRIPT ALEF
  p+ 067E    -- ARABIC LETTER PEH
  v+ 06A4    -- ARABIC LETTER VEH
  gf 06AF    -- ARABIC LETTER GAF
  0a 06F0    -- EXTENDED ARABIC-INDIC DIGIT ZERO
  1a 06F1    -- EXTENDED ARABIC-INDIC DIGIT ONE
  2a 06F2    -- EXTENDED ARABIC-INDIC DIGIT TWO
  3a 06F3    -- EXTENDED ARABIC-INDIC DIGIT THREE
  4a 06F4    -- EXTENDED ARABIC-INDIC DIGIT FOUR
  5a 06F5    -- EXTENDED ARABIC-INDIC DIGIT FIVE
  6a 06F6    -- EXTENDED ARABIC-INDIC DIGIT SIX
  7a 06F7    -- EXTENDED ARABIC-INDIC DIGIT SEVEN
  8a 06F8    -- EXTENDED ARABIC-INDIC DIGIT EIGHT
  9a 06F9    -- EXTENDED ARABIC-INDIC DIGIT NINE
  B. 1E02    -- LATIN CAPITAL LETTER B WITH DOT ABOVE
  b. 1E03    -- LATIN SMALL LETTER B WITH DOT ABOVE
  B_ 1E06    -- LATIN CAPITAL LETTER B WITH LINE BELOW
  b_ 1E07    -- LATIN SMALL LETTER B WITH LINE BELOW
  D. 1E0A    -- LATIN CAPITAL LETTER D WITH DOT ABOVE
  d. 1E0B    -- LATIN SMALL LETTER D WITH DOT ABOVE
  D_ 1E0E    -- LATIN CAPITAL LETTER D WITH LINE BELOW
  d_ 1E0F    -- LATIN SMALL LETTER D WITH LINE BELOW
  D, 1E10    -- LATIN CAPITAL LETTER D WITH CEDILLA
  d, 1E11    -- LATIN SMALL LETTER D WITH CEDILLA
  F. 1E1E    -- LATIN CAPITAL LETTER F WITH DOT ABOVE
  f. 1E1F    -- LATIN SMALL LETTER F WITH DOT ABOVE
  G- 1E20    -- LATIN CAPITAL LETTER G WITH MACRON
  g- 1E21    -- LATIN SMALL LETTER G WITH MACRON
  H. 1E22    -- LATIN CAPITAL LETTER H WITH DOT ABOVE
  h. 1E23    -- LATIN SMALL LETTER H WITH DOT ABOVE
  H: 1E26    -- LATIN CAPITAL LETTER H WITH DIAERESIS
  h: 1E27    -- LATIN SMALL LETTER H WITH DIAERESIS
  H, 1E28    -- LATIN CAPITAL LETTER H WITH CEDILLA
  h, 1E29    -- LATIN SMALL LETTER H WITH CEDILLA
  K' 1E30    -- LATIN CAPITAL LETTER K WITH ACUTE
  k' 1E31    -- LATIN SMALL LETTER K WITH ACUTE
  K_ 1E34    -- LATIN CAPITAL LETTER K WITH LINE BELOW
  k_ 1E35    -- LATIN SMALL LETTER K WITH LINE BELOW
  L_ 1E3A    -- LATIN CAPITAL LETTER L WITH LINE BELOW
  l_ 1E3B    -- LATIN SMALL LETTER L WITH LINE BELOW
  M' 1E3E    -- LATIN CAPITAL LETTER M WITH ACUTE
  m' 1E3F    -- LATIN SMALL LETTER M WITH ACUTE
  M. 1E40    -- LATIN CAPITAL LETTER M WITH DOT ABOVE
  m. 1E41    -- LATIN SMALL LETTER M WITH DOT ABOVE
  N. 1E44    -- LATIN CAPITAL LETTER N WITH DOT ABOVE `
  n. 1E45    -- LATIN SMALL LETTER N WITH DOT ABOVE `
  N_ 1E48    -- LATIN CAPITAL LETTER N WITH LINE BELOW `
  n_ 1E49    -- LATIN SMALL LETTER N WITH LINE BELOW `
  P' 1E54    -- LATIN CAPITAL LETTER P WITH ACUTE
  p' 1E55    -- LATIN SMALL LETTER P WITH ACUTE
  P. 1E56    -- LATIN CAPITAL LETTER P WITH DOT ABOVE
  p. 1E57    -- LATIN SMALL LETTER P WITH DOT ABOVE
  R. 1E58    -- LATIN CAPITAL LETTER R WITH DOT ABOVE
  r. 1E59    -- LATIN SMALL LETTER R WITH DOT ABOVE
  R_ 1E5E    -- LATIN CAPITAL LETTER R WITH LINE BELOW
  r_ 1E5F    -- LATIN SMALL LETTER R WITH LINE BELOW
  S. 1E60    -- LATIN CAPITAL LETTER S WITH DOT ABOVE
  s. 1E61    -- LATIN SMALL LETTER S WITH DOT ABOVE
  T. 1E6A    -- LATIN CAPITAL LETTER T WITH DOT ABOVE
  t. 1E6B    -- LATIN SMALL LETTER T WITH DOT ABOVE
  T_ 1E6E    -- LATIN CAPITAL LETTER T WITH LINE BELOW
  t_ 1E6F    -- LATIN SMALL LETTER T WITH LINE BELOW
  V? 1E7C    -- LATIN CAPITAL LETTER V WITH TILDE
  v? 1E7D    -- LATIN SMALL LETTER V WITH TILDE
  W! 1E80    -- LATIN CAPITAL LETTER W WITH GRAVE
  w! 1E81    -- LATIN SMALL LETTER W WITH GRAVE
  W' 1E82    -- LATIN CAPITAL LETTER W WITH ACUTE
  w' 1E83    -- LATIN SMALL LETTER W WITH ACUTE
  W: 1E84    -- LATIN CAPITAL LETTER W WITH DIAERESIS
  w: 1E85    -- LATIN SMALL LETTER W WITH DIAERESIS
  W. 1E86    -- LATIN CAPITAL LETTER W WITH DOT ABOVE
  w. 1E87    -- LATIN SMALL LETTER W WITH DOT ABOVE
  X. 1E8A    -- LATIN CAPITAL LETTER X WITH DOT ABOVE
  x. 1E8B    -- LATIN SMALL LETTER X WITH DOT ABOVE
  X: 1E8C    -- LATIN CAPITAL LETTER X WITH DIAERESIS
  x: 1E8D    -- LATIN SMALL LETTER X WITH DIAERESIS
  Y. 1E8E    -- LATIN CAPITAL LETTER Y WITH DOT ABOVE
  y. 1E8F    -- LATIN SMALL LETTER Y WITH DOT ABOVE
  Z> 1E90    -- LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
  z> 1E91    -- LATIN SMALL LETTER Z WITH CIRCUMFLEX
  Z_ 1E94    -- LATIN CAPITAL LETTER Z WITH LINE BELOW
  z_ 1E95    -- LATIN SMALL LETTER Z WITH LINE BELOW
  h_ 1E96    -- LATIN SMALL LETTER H WITH LINE BELOW
  t: 1E97    -- LATIN SMALL LETTER T WITH DIAERESIS
  w0 1E98    -- LATIN SMALL LETTER W WITH RING ABOVE
  y0 1E99    -- LATIN SMALL LETTER Y WITH RING ABOVE
  A2 1EA2    -- LATIN CAPITAL LETTER A WITH HOOK ABOVE
  a2 1EA3    -- LATIN SMALL LETTER A WITH HOOK ABOVE
  E2 1EBA    -- LATIN CAPITAL LETTER E WITH HOOK ABOVE
  e2 1EBB    -- LATIN SMALL LETTER E WITH HOOK ABOVE
  E? 1EBC    -- LATIN CAPITAL LETTER E WITH TILDE
  e? 1EBD    -- LATIN SMALL LETTER E WITH TILDE
  I2 1EC8    -- LATIN CAPITAL LETTER I WITH HOOK ABOVE
  i2 1EC9    -- LATIN SMALL LETTER I WITH HOOK ABOVE
  O2 1ECE    -- LATIN CAPITAL LETTER O WITH HOOK ABOVE
  o2 1ECF    -- LATIN SMALL LETTER O WITH HOOK ABOVE
  U2 1EE6    -- LATIN CAPITAL LETTER U WITH HOOK ABOVE
  u2 1EE7    -- LATIN SMALL LETTER U WITH HOOK ABOVE
  Y! 1EF2    -- LATIN CAPITAL LETTER Y WITH GRAVE
  y! 1EF3    -- LATIN SMALL LETTER Y WITH GRAVE
  Y2 1EF6    -- LATIN CAPITAL LETTER Y WITH HOOK ABOVE
  y2 1EF7    -- LATIN SMALL LETTER Y WITH HOOK ABOVE
  Y? 1EF8    -- LATIN CAPITAL LETTER Y WITH TILDE
  y? 1EF9    -- LATIN SMALL LETTER Y WITH TILDE
  ;' 1F00    -- GREEK SMALL LETTER ALPHA WITH PSILI
  ,' 1F01    -- GREEK SMALL LETTER ALPHA WITH DASIA
  ;! 1F02    -- GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
  ,! 1F03    -- GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
  ?; 1F04    -- GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
  ?, 1F05    -- GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
  !: 1F06    -- GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
  ?: 1F07    -- GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
  1N 2002    -- EN SPACE
  1M 2003    -- EM SPACE
  3M 2004    -- THREE-PER-EM SPACE
  4M 2005    -- FOUR-PER-EM SPACE
  6M 2006    -- SIX-PER-EM SPACE
  1T 2009    -- THIN SPACE
  1H 200A    -- HAIR SPACE
  -1 2010    -- HYPHEN
  -N 2013    -- EN DASH `
  -M 2014    -- EM DASH
  -3 2015    -- HORIZONTAL BAR
  !2 2016    -- DOUBLE VERTICAL LINE
  =2 2017    -- DOUBLE LOW LINE
  '6 2018    -- LEFT SINGLE QUOTATION MARK
  '9 2019    -- RIGHT SINGLE QUOTATION MARK
  .9 201A    -- SINGLE LOW-9 QUOTATION MARK
  9' 201B    -- SINGLE HIGH-REVERSED-9 QUOTATION MARK
  "6 201C    -- LEFT DOUBLE QUOTATION MARK
  "9 201D    -- RIGHT DOUBLE QUOTATION MARK
  :9 201E    -- DOUBLE LOW-9 QUOTATION MARK
  9" 201F    -- DOUBLE HIGH-REVERSED-9 QUOTATION MARK
  /- 2020    -- DAGGER
  /= 2021    -- DOUBLE DAGGER
  .. 2025    -- TWO DOT LEADER
  %0 2030    -- PER MILLE SIGN
  1' 2032    -- PRIME
  2' 2033    -- DOUBLE PRIME
  3' 2034    -- TRIPLE PRIME
  1" 2035    -- REVERSED PRIME
  2" 2036    -- REVERSED DOUBLE PRIME
  3" 2037    -- REVERSED TRIPLE PRIME
  Ca 2038    -- CARET
  <1 2039    -- SINGLE LEFT-POINTING ANGLE QUOTATION MARK
  >1 203A    -- SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
  :X 203B    -- REFERENCE MARK
  '- 203E    -- OVERLINE
  /f 2044    -- FRACTION SLASH
  0S 2070    -- SUPERSCRIPT ZERO
  4S 2074    -- SUPERSCRIPT FOUR
  5S 2075    -- SUPERSCRIPT FIVE
  6S 2076    -- SUPERSCRIPT SIX
  7S 2077    -- SUPERSCRIPT SEVEN
  8S 2078    -- SUPERSCRIPT EIGHT
  9S 2079    -- SUPERSCRIPT NINE
  +S 207A    -- SUPERSCRIPT PLUS SIGN
  -S 207B    -- SUPERSCRIPT MINUS
  =S 207C    -- SUPERSCRIPT EQUALS SIGN
  (S 207D    -- SUPERSCRIPT LEFT PARENTHESIS
  )S 207E    -- SUPERSCRIPT RIGHT PARENTHESIS
  nS 207F    -- SUPERSCRIPT LATIN SMALL LETTER N `
  0s 2080    -- SUBSCRIPT ZERO
  1s 2081    -- SUBSCRIPT ONE
  2s 2082    -- SUBSCRIPT TWO
  3s 2083    -- SUBSCRIPT THREE
  4s 2084    -- SUBSCRIPT FOUR
  5s 2085    -- SUBSCRIPT FIVE
  6s 2086    -- SUBSCRIPT SIX
  7s 2087    -- SUBSCRIPT SEVEN
  8s 2088    -- SUBSCRIPT EIGHT
  9s 2089    -- SUBSCRIPT NINE
  +s 208A    -- SUBSCRIPT PLUS SIGN
  -s 208B    -- SUBSCRIPT MINUS
  =s 208C    -- SUBSCRIPT EQUALS SIGN
  (s 208D    -- SUBSCRIPT LEFT PARENTHESIS
  )s 208E    -- SUBSCRIPT RIGHT PARENTHESIS
  Li 20A4    -- LIRA SIGN
  Pt 20A7    -- PESETA SIGN
  W= 20A9    -- WON SIGN
  Eu 20AC    -- EURO SIGN
  oC 2103    -- DEGREE CELSIUS
  co 2105    -- CARE OF
  oF 2109    -- DEGREE FAHRENHEIT
  N0 2116    -- NUMERO SIGN
  PO 2117    -- SOUND RECORDING COPYRIGHT
  Rx 211E    -- PRESCRIPTION TAKE
  SM 2120    -- SERVICE MARK
  TM 2122    -- TRADE MARK SIGN
  Om 2126    -- OHM SIGN
  AO 212B    -- ANGSTROM SIGN
  13 2153    -- VULGAR FRACTION ONE THIRD
  23 2154    -- VULGAR FRACTION TWO THIRDS
  15 2155    -- VULGAR FRACTION ONE FIFTH
  25 2156    -- VULGAR FRACTION TWO FIFTHS
  35 2157    -- VULGAR FRACTION THREE FIFTHS
  45 2158    -- VULGAR FRACTION FOUR FIFTHS
  16 2159    -- VULGAR FRACTION ONE SIXTH
  56 215A    -- VULGAR FRACTION FIVE SIXTHS
  18 215B    -- VULGAR FRACTION ONE EIGHTH
  38 215C    -- VULGAR FRACTION THREE EIGHTHS
  58 215D    -- VULGAR FRACTION FIVE EIGHTHS
  78 215E    -- VULGAR FRACTION SEVEN EIGHTHS
  1R 2160    -- ROMAN NUMERAL ONE
  2R 2161    -- ROMAN NUMERAL TWO
  3R 2162    -- ROMAN NUMERAL THREE
  4R 2163    -- ROMAN NUMERAL FOUR
  5R 2164    -- ROMAN NUMERAL FIVE
  6R 2165    -- ROMAN NUMERAL SIX
  7R 2166    -- ROMAN NUMERAL SEVEN
  8R 2167    -- ROMAN NUMERAL EIGHT
  9R 2168    -- ROMAN NUMERAL NINE
  aR 2169    -- ROMAN NUMERAL TEN
  bR 216A    -- ROMAN NUMERAL ELEVEN
  cR 216B    -- ROMAN NUMERAL TWELVE
  1r 2170    -- SMALL ROMAN NUMERAL ONE
  2r 2171    -- SMALL ROMAN NUMERAL TWO
  3r 2172    -- SMALL ROMAN NUMERAL THREE
  4r 2173    -- SMALL ROMAN NUMERAL FOUR
  5r 2174    -- SMALL ROMAN NUMERAL FIVE
  6r 2175    -- SMALL ROMAN NUMERAL SIX
  7r 2176    -- SMALL ROMAN NUMERAL SEVEN
  8r 2177    -- SMALL ROMAN NUMERAL EIGHT
  9r 2178    -- SMALL ROMAN NUMERAL NINE
  ar 2179    -- SMALL ROMAN NUMERAL TEN
  br 217A    -- SMALL ROMAN NUMERAL ELEVEN
  cr 217B    -- SMALL ROMAN NUMERAL TWELVE
  <- 2190    -- LEFTWARDS ARROW
  -! 2191    -- UPWARDS ARROW
  -> 2192    -- RIGHTWARDS ARROW
  -v 2193    -- DOWNWARDS ARROW
  <> 2194    -- LEFT RIGHT ARROW
  UD 2195    -- UP DOWN ARROW
  <= 21D0    -- LEFTWARDS DOUBLE ARROW
  => 21D2    -- RIGHTWARDS DOUBLE ARROW
  == 21D4    -- LEFT RIGHT DOUBLE ARROW
  FA 2200    -- FOR ALL
  dP 2202    -- PARTIAL DIFFERENTIAL
  TE 2203    -- THERE EXISTS
  /0 2205    -- EMPTY SET
  DE 2206    -- INCREMENT
  NB 2207    -- NABLA
  (- 2208    -- ELEMENT OF
  -) 220B    -- CONTAINS AS MEMBER
  *P 220F    -- N-ARY PRODUCT `
  +Z 2211    -- N-ARY SUMMATION `
  -2 2212    -- MINUS SIGN
  -+ 2213    -- MINUS-OR-PLUS SIGN
  *- 2217    -- ASTERISK OPERATOR
  Ob 2218    -- RING OPERATOR
  Sb 2219    -- BULLET OPERATOR
  RT 221A    -- SQUARE ROOT
  0( 221D    -- PROPORTIONAL TO
  00 221E    -- INFINITY
  -L 221F    -- RIGHT ANGLE
  -V 2220    -- ANGLE
  PP 2225    -- PARALLEL TO
  AN 2227    -- LOGICAL AND
  OR 2228    -- LOGICAL OR
  (U 2229    -- INTERSECTION
  )U 222A    -- UNION
  In 222B    -- INTEGRAL
  DI 222C    -- DOUBLE INTEGRAL
  Io 222E    -- CONTOUR INTEGRAL
  .: 2234    -- THEREFORE
  :. 2235    -- BECAUSE
  :R 2236    -- RATIO
  :: 2237    -- PROPORTION
  ?1 223C    -- TILDE OPERATOR
  CG 223E    -- INVERTED LAZY S
  ?- 2243    -- ASYMPTOTICALLY EQUAL TO
  ?= 2245    -- APPROXIMATELY EQUAL TO
  ?2 2248    -- ALMOST EQUAL TO
  =? 224C    -- ALL EQUAL TO
  HI 2253    -- IMAGE OF OR APPROXIMATELY EQUAL TO
  != 2260    -- NOT EQUAL TO
  =3 2261    -- IDENTICAL TO
  =< 2264    -- LESS-THAN OR EQUAL TO
  >= 2265    -- GREATER-THAN OR EQUAL TO
  <* 226A    -- MUCH LESS-THAN
  *> 226B    -- MUCH GREATER-THAN
  !< 226E    -- NOT LESS-THAN
  !> 226F    -- NOT GREATER-THAN
  (C 2282    -- SUBSET OF
  )C 2283    -- SUPERSET OF
  (_ 2286    -- SUBSET OF OR EQUAL TO
  )_ 2287    -- SUPERSET OF OR EQUAL TO
  0. 2299    -- CIRCLED DOT OPERATOR
  02 229A    -- CIRCLED RING OPERATOR
  -T 22A5    -- UP TACK
  .P 22C5    -- DOT OPERATOR
  :3 22EE    -- VERTICAL ELLIPSIS
  .3 22EF    -- MIDLINE HORIZONTAL ELLIPSIS
  Eh 2302    -- HOUSE
  <7 2308    -- LEFT CEILING
  >7 2309    -- RIGHT CEILING
  7< 230A    -- LEFT FLOOR
  7> 230B    -- RIGHT FLOOR
  NI 2310    -- REVERSED NOT SIGN
  (A 2312    -- ARC
  TR 2315    -- TELEPHONE RECORDER
  Iu 2320    -- TOP HALF INTEGRAL
  Il 2321    -- BOTTOM HALF INTEGRAL
  </ 2329    -- LEFT-POINTING ANGLE BRACKET
  /> 232A    -- RIGHT-POINTING ANGLE BRACKET
  Vs 2423    -- OPEN BOX
  1h 2440    -- OCR HOOK
  3h 2441    -- OCR CHAIR
  2h 2442    -- OCR FORK
  4h 2443    -- OCR INVERTED FORK
  1j 2446    -- OCR BRANCH BANK IDENTIFICATION
  2j 2447    -- OCR AMOUNT OF CHECK
  3j 2448    -- OCR DASH
  4j 2449    -- OCR CUSTOMER ACCOUNT NUMBER
  1. 2488    -- DIGIT ONE FULL STOP
  2. 2489    -- DIGIT TWO FULL STOP
  3. 248A    -- DIGIT THREE FULL STOP
  4. 248B    -- DIGIT FOUR FULL STOP
  5. 248C    -- DIGIT FIVE FULL STOP
  6. 248D    -- DIGIT SIX FULL STOP
  7. 248E    -- DIGIT SEVEN FULL STOP
  8. 248F    -- DIGIT EIGHT FULL STOP
  9. 2490    -- DIGIT NINE FULL STOP
  hh 2500    -- BOX DRAWINGS LIGHT HORIZONTAL
  HH 2501    -- BOX DRAWINGS HEAVY HORIZONTAL
  vv 2502    -- BOX DRAWINGS LIGHT VERTICAL
  VV 2503    -- BOX DRAWINGS HEAVY VERTICAL
  3- 2504    -- BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
  3_ 2505    -- BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
  3! 2506    -- BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
  3/ 2507    -- BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
  4- 2508    -- BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
  4_ 2509    -- BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
  4! 250A    -- BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
  4/ 250B    -- BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
  dr 250C    -- BOX DRAWINGS LIGHT DOWN AND RIGHT
  dR 250D    -- BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
  Dr 250E    -- BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
  DR 250F    -- BOX DRAWINGS HEAVY DOWN AND RIGHT
  dl 2510    -- BOX DRAWINGS LIGHT DOWN AND LEFT
  dL 2511    -- BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
  Dl 2512    -- BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
  LD 2513    -- BOX DRAWINGS HEAVY DOWN AND LEFT
  ur 2514    -- BOX DRAWINGS LIGHT UP AND RIGHT
  uR 2515    -- BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
  Ur 2516    -- BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
  UR 2517    -- BOX DRAWINGS HEAVY UP AND RIGHT
  ul 2518    -- BOX VOICED SOUND MARKDRAWINGS LIGHT UP AND LEFT
  uL 2519    -- BOX DRAWINGS UP LIGHT AND LEFT HEAVY
  Ul 251A    -- BOX DRAWINGS UP HEAVY AND LEFT LIGHT
  UL 251B    -- BOX DRAWINGS HEAVY UP AND LEFT
  vr 251C    -- BOX DRAWINGS LIGHT VERTICAL AND RIGHT
  vR 251D    -- BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY
  Vr 2520    -- BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT
  VR 2523    -- BOX DRAWINGS HEAVY VERTICAL AND RIGHT
  vl 2524    -- BOX DRAWINGS LIGHT VERTICAL AND LEFT
  vL 2525    -- BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY
  Vl 2528    -- BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT
  VL 252B    -- BOX DRAWINGS HEAVY VERTICAL AND LEFT
  dh 252C    -- BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
  dH 252F    -- BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY
  Dh 2530    -- BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT
  DH 2533    -- BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
  uh 2534    -- BOX DRAWINGS LIGHT UP AND HORIZONTAL
  uH 2537    -- BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY
  Uh 2538    -- BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT
  UH 253B    -- BOX DRAWINGS HEAVY UP AND HORIZONTAL
  vh 253C    -- BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
  vH 253F    -- BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY
  Vh 2542    -- BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT
  VH 254B    -- BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  FD 2571    -- BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
  BD 2572    -- BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
  TB 2580    -- UPPER HALF BLOCK
  LB 2584    -- LOWER HALF BLOCK
  FB 2588    -- FULL BLOCK
  lB 258C    -- LEFT HALF BLOCK
  RB 2590    -- RIGHT HALF BLOCK
  .S 2591    -- LIGHT SHADE
  :S 2592    -- MEDIUM SHADE
  ?S 2593    -- DARK SHADE
  fS 25A0    -- BLACK SQUARE
  OS 25A1    -- WHITE SQUARE
  RO 25A2    -- WHITE SQUARE WITH ROUNDED CORNERS
  Rr 25A3    -- WHITE SQUARE CONTAINING BLACK SMALL SQUARE
  RF 25A4    -- SQUARE WITH HORIZONTAL FILL
  RY 25A5    -- SQUARE WITH VERTICAL FILL
  RH 25A6    -- SQUARE WITH ORTHOGONAL CROSSHATCH FILL
  RZ 25A7    -- SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL
  RK 25A8    -- SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL
  RX 25A9    -- SQUARE WITH DIAGONAL CROSSHATCH FILL
  sB 25AA    -- BLACK SMALL SQUARE
  SR 25AC    -- BLACK RECTANGLE
  Or 25AD    -- WHITE RECTANGLE
  UT 25B2    -- BLACK UP-POINTING TRIANGLE
  uT 25B3    -- WHITE UP-POINTING TRIANGLE
  PR 25B6    -- BLACK RIGHT-POINTING TRIANGLE
  Tr 25B7    -- WHITE RIGHT-POINTING TRIANGLE
  Dt 25BC    -- BLACK DOWN-POINTING TRIANGLE
  dT 25BD    -- WHITE DOWN-POINTING TRIANGLE
  PL 25C0    -- BLACK LEFT-POINTING TRIANGLE
  Tl 25C1    -- WHITE LEFT-POINTING TRIANGLE
  Db 25C6    -- BLACK DIAMOND
  Dw 25C7    -- WHITE DIAMOND
  LZ 25CA    -- LOZENGE
  0m 25CB    -- WHITE CIRCLE
  0o 25CE    -- BULLSEYE
  0M 25CF    -- BLACK CIRCLE
  0L 25D0    -- CIRCLE WITH LEFT HALF BLACK
  0R 25D1    -- CIRCLE WITH RIGHT HALF BLACK
  Sn 25D8    -- INVERSE BULLET
  Ic 25D9    -- INVERSE WHITE CIRCLE
  Fd 25E2    -- BLACK LOWER RIGHT TRIANGLE
  Bd 25E3    -- BLACK LOWER LEFT TRIANGLE
  *2 2605    -- BLACK STAR
  *1 2606    -- WHITE STAR
  <H 261C    -- WHITE LEFT POINTING INDEX
  >H 261E    -- WHITE RIGHT POINTING INDEX
  0u 263A    -- WHITE SMILING FACE
  0U 263B    -- BLACK SMILING FACE
  SU 263C    -- WHITE SUN WITH RAYS
  Fm 2640    -- FEMALE SIGN
  Ml 2642    -- MALE SIGN
  cS 2660    -- BLACK SPADE SUIT
  cH 2661    -- WHITE HEART SUIT
  cD 2662    -- WHITE DIAMOND SUIT
  cC 2663    -- BLACK CLUB SUIT
  Md 2669    -- QUARTER NOTE `
  M8 266A    -- EIGHTH NOTE `
  M2 266B    -- BEAMED EIGHTH NOTES
  Mb 266D    -- MUSIC FLAT SIGN
  Mx 266E    -- MUSIC NATURAL SIGN
  MX 266F    -- MUSIC SHARP SIGN
  OK 2713    -- CHECK MARK
  XX 2717    -- BALLOT X
  -X 2720    -- MALTESE CROSS
  IS 3000    -- IDEOGRAPHIC SPACE
  ,_ 3001    -- IDEOGRAPHIC COMMA
  ._ 3002    -- IDEOGRAPHIC FULL STOP
  +" 3003    -- DITTO MARK
  +_ 3004    -- JAPANESE INDUSTRIAL STANDARD SYMBOL
  *_ 3005    -- IDEOGRAPHIC ITERATION MARK
  ;_ 3006    -- IDEOGRAPHIC CLOSING MARK
  0_ 3007    -- IDEOGRAPHIC NUMBER ZERO
  <+ 300A    -- LEFT DOUBLE ANGLE BRACKET
  >+ 300B    -- RIGHT DOUBLE ANGLE BRACKET
  <' 300C    -- LEFT CORNER BRACKET
  >' 300D    -- RIGHT CORNER BRACKET
  <" 300E    -- LEFT WHITE CORNER BRACKET
  >" 300F    -- RIGHT WHITE CORNER BRACKET
  (" 3010    -- LEFT BLACK LENTICULAR BRACKET
  )" 3011    -- RIGHT BLACK LENTICULAR BRACKET
  =T 3012    -- POSTAL MARK
  =_ 3013    -- GETA MARK
  (' 3014    -- LEFT TORTOISE SHELL BRACKET
  )' 3015    -- RIGHT TORTOISE SHELL BRACKET
  (I 3016    -- LEFT WHITE LENTICULAR BRACKET
  )I 3017    -- RIGHT WHITE LENTICULAR BRACKET
  -? 301C    -- WAVE DASH
  A5 3041    -- HIRAGANA LETTER SMALL A
  a5 3042    -- HIRAGANA LETTER A
  I5 3043    -- HIRAGANA LETTER SMALL I
  i5 3044    -- HIRAGANA LETTER I
  U5 3045    -- HIRAGANA LETTER SMALL U
  u5 3046    -- HIRAGANA LETTER U
  E5 3047    -- HIRAGANA LETTER SMALL E
  e5 3048    -- HIRAGANA LETTER E
  O5 3049    -- HIRAGANA LETTER SMALL O
  o5 304A    -- HIRAGANA LETTER O
  ka 304B    -- HIRAGANA LETTER KA
  ga 304C    -- HIRAGANA LETTER GA
  ki 304D    -- HIRAGANA LETTER KI
  gi 304E    -- HIRAGANA LETTER GI
  ku 304F    -- HIRAGANA LETTER KU
  gu 3050    -- HIRAGANA LETTER GU
  ke 3051    -- HIRAGANA LETTER KE
  ge 3052    -- HIRAGANA LETTER GE
  ko 3053    -- HIRAGANA LETTER KO
  go 3054    -- HIRAGANA LETTER GO
  sa 3055    -- HIRAGANA LETTER SA
  za 3056    -- HIRAGANA LETTER ZA
  si 3057    -- HIRAGANA LETTER SI
  zi 3058    -- HIRAGANA LETTER ZI
  su 3059    -- HIRAGANA LETTER SU
  zu 305A    -- HIRAGANA LETTER ZU
  se 305B    -- HIRAGANA LETTER SE
  ze 305C    -- HIRAGANA LETTER ZE
  so 305D    -- HIRAGANA LETTER SO
  zo 305E    -- HIRAGANA LETTER ZO
  ta 305F    -- HIRAGANA LETTER TA
  da 3060    -- HIRAGANA LETTER DA
  ti 3061    -- HIRAGANA LETTER TI
  di 3062    -- HIRAGANA LETTER DI
  tU 3063    -- HIRAGANA LETTER SMALL TU
  tu 3064    -- HIRAGANA LETTER TU
  du 3065    -- HIRAGANA LETTER DU
  te 3066    -- HIRAGANA LETTER TE
  de 3067    -- HIRAGANA LETTER DE
  to 3068    -- HIRAGANA LETTER TO
  do 3069    -- HIRAGANA LETTER DO
  na 306A    -- HIRAGANA LETTER NA
  ni 306B    -- HIRAGANA LETTER NI
  nu 306C    -- HIRAGANA LETTER NU
  ne 306D    -- HIRAGANA LETTER NE
  no 306E    -- HIRAGANA LETTER NO
  ha 306F    -- HIRAGANA LETTER HA
  ba 3070    -- HIRAGANA LETTER BA
  pa 3071    -- HIRAGANA LETTER PA
  hi 3072    -- HIRAGANA LETTER HI
  bi 3073    -- HIRAGANA LETTER BI
  pi 3074    -- HIRAGANA LETTER PI
  hu 3075    -- HIRAGANA LETTER HU
  bu 3076    -- HIRAGANA LETTER BU
  pu 3077    -- HIRAGANA LETTER PU
  he 3078    -- HIRAGANA LETTER HE
  be 3079    -- HIRAGANA LETTER BE
  pe 307A    -- HIRAGANA LETTER PE
  ho 307B    -- HIRAGANA LETTER HO
  bo 307C    -- HIRAGANA LETTER BO
  po 307D    -- HIRAGANA LETTER PO
  ma 307E    -- HIRAGANA LETTER MA
  mi 307F    -- HIRAGANA LETTER MI
  mu 3080    -- HIRAGANA LETTER MU
  me 3081    -- HIRAGANA LETTER ME
  mo 3082    -- HIRAGANA LETTER MO
  yA 3083    -- HIRAGANA LETTER SMALL YA
  ya 3084    -- HIRAGANA LETTER YA
  yU 3085    -- HIRAGANA LETTER SMALL YU
  yu 3086    -- HIRAGANA LETTER YU
  yO 3087    -- HIRAGANA LETTER SMALL YO
  yo 3088    -- HIRAGANA LETTER YO
  ra 3089    -- HIRAGANA LETTER RA
  ri 308A    -- HIRAGANA LETTER RI
  ru 308B    -- HIRAGANA LETTER RU
  re 308C    -- HIRAGANA LETTER RE
  ro 308D    -- HIRAGANA LETTER RO
  wA 308E    -- HIRAGANA LETTER SMALL WA
  wa 308F    -- HIRAGANA LETTER WA
  wi 3090    -- HIRAGANA LETTER WI
  we 3091    -- HIRAGANA LETTER WE
  wo 3092    -- HIRAGANA LETTER WO
  n5 3093    -- HIRAGANA LETTER N `
  vu 3094    -- HIRAGANA LETTER VU
  "5 309B    -- KATAKANA-HIRAGANA VOICED SOUND MARK
  05 309C    -- KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  *5 309D    -- HIRAGANA ITERATION MARK
  +5 309E    -- HIRAGANA VOICED ITERATION MARK
  a6 30A1    -- KATAKANA LETTER SMALL A
  A6 30A2    -- KATAKANA LETTER A
  i6 30A3    -- KATAKANA LETTER SMALL I
  I6 30A4    -- KATAKANA LETTER I
  u6 30A5    -- KATAKANA LETTER SMALL U
  U6 30A6    -- KATAKANA LETTER U
  e6 30A7    -- KATAKANA LETTER SMALL E
  E6 30A8    -- KATAKANA LETTER E
  o6 30A9    -- KATAKANA LETTER SMALL O
  O6 30AA    -- KATAKANA LETTER O
  Ka 30AB    -- KATAKANA LETTER KA
  Ga 30AC    -- KATAKANA LETTER GA
  Ki 30AD    -- KATAKANA LETTER KI
  Gi 30AE    -- KATAKANA LETTER GI
  Ku 30AF    -- KATAKANA LETTER KU
  Gu 30B0    -- KATAKANA LETTER GU
  Ke 30B1    -- KATAKANA LETTER KE
  Ge 30B2    -- KATAKANA LETTER GE
  Ko 30B3    -- KATAKANA LETTER KO
  Go 30B4    -- KATAKANA LETTER GO
  Sa 30B5    -- KATAKANA LETTER SA
  Za 30B6    -- KATAKANA LETTER ZA
  Si 30B7    -- KATAKANA LETTER SI
  Zi 30B8    -- KATAKANA LETTER ZI
  Su 30B9    -- KATAKANA LETTER SU
  Zu 30BA    -- KATAKANA LETTER ZU
  Se 30BB    -- KATAKANA LETTER SE
  Ze 30BC    -- KATAKANA LETTER ZE
  So 30BD    -- KATAKANA LETTER SO
  Zo 30BE    -- KATAKANA LETTER ZO
  Ta 30BF    -- KATAKANA LETTER TA
  Da 30C0    -- KATAKANA LETTER DA
  Ti 30C1    -- KATAKANA LETTER TI
  Di 30C2    -- KATAKANA LETTER DI
  TU 30C3    -- KATAKANA LETTER SMALL TU
  Tu 30C4    -- KATAKANA LETTER TU
  Du 30C5    -- KATAKANA LETTER DU
  Te 30C6    -- KATAKANA LETTER TE
  De 30C7    -- KATAKANA LETTER DE
  To 30C8    -- KATAKANA LETTER TO
  Do 30C9    -- KATAKANA LETTER DO
  Na 30CA    -- KATAKANA LETTER NA
  Ni 30CB    -- KATAKANA LETTER NI
  Nu 30CC    -- KATAKANA LETTER NU
  Ne 30CD    -- KATAKANA LETTER NE
  No 30CE    -- KATAKANA LETTER NO
  Ha 30CF    -- KATAKANA LETTER HA
  Ba 30D0    -- KATAKANA LETTER BA
  Pa 30D1    -- KATAKANA LETTER PA
  Hi 30D2    -- KATAKANA LETTER HI
  Bi 30D3    -- KATAKANA LETTER BI
  Pi 30D4    -- KATAKANA LETTER PI
  Hu 30D5    -- KATAKANA LETTER HU
  Bu 30D6    -- KATAKANA LETTER BU
  Pu 30D7    -- KATAKANA LETTER PU
  He 30D8    -- KATAKANA LETTER HE
  Be 30D9    -- KATAKANA LETTER BE
  Pe 30DA    -- KATAKANA LETTER PE
  Ho 30DB    -- KATAKANA LETTER HO
  Bo 30DC    -- KATAKANA LETTER BO
  Po 30DD    -- KATAKANA LETTER PO
  Ma 30DE    -- KATAKANA LETTER MA
  Mi 30DF    -- KATAKANA LETTER MI
  Mu 30E0    -- KATAKANA LETTER MU
  Me 30E1    -- KATAKANA LETTER ME
  Mo 30E2    -- KATAKANA LETTER MO
  YA 30E3    -- KATAKANA LETTER SMALL YA
  Ya 30E4    -- KATAKANA LETTER YA
  YU 30E5    -- KATAKANA LETTER SMALL YU
  Yu 30E6    -- KATAKANA LETTER YU
  YO 30E7    -- KATAKANA LETTER SMALL YO
  Yo 30E8    -- KATAKANA LETTER YO
  Ra 30E9    -- KATAKANA LETTER RA
  Ri 30EA    -- KATAKANA LETTER RI
  Ru 30EB    -- KATAKANA LETTER RU
  Re 30EC    -- KATAKANA LETTER RE
  Ro 30ED    -- KATAKANA LETTER RO
  WA 30EE    -- KATAKANA LETTER SMALL WA
  Wa 30EF    -- KATAKANA LETTER WA
  Wi 30F0    -- KATAKANA LETTER WI
  We 30F1    -- KATAKANA LETTER WE
  Wo 30F2    -- KATAKANA LETTER WO
  N6 30F3    -- KATAKANA LETTER N `
  Vu 30F4    -- KATAKANA LETTER VU
  KA 30F5    -- KATAKANA LETTER SMALL KA
  KE 30F6    -- KATAKANA LETTER SMALL KE
  Va 30F7    -- KATAKANA LETTER VA
  Vi 30F8    -- KATAKANA LETTER VI
  Ve 30F9    -- KATAKANA LETTER VE
  Vo 30FA    -- KATAKANA LETTER VO
  .6 30FB    -- KATAKANA MIDDLE DOT
  -6 30FC    -- KATAKANA-HIRAGANA PROLONGED SOUND MARK
  *6 30FD    -- KATAKANA ITERATION MARK
  +6 30FE    -- KATAKANA VOICED ITERATION MARK
  b4 3105    -- BOPOMOFO LETTER B
  p4 3106    -- BOPOMOFO LETTER P
  m4 3107    -- BOPOMOFO LETTER M
  f4 3108    -- BOPOMOFO LETTER F
  d4 3109    -- BOPOMOFO LETTER D
  t4 310A    -- BOPOMOFO LETTER T
  n4 310B    -- BOPOMOFO LETTER N `
  l4 310C    -- BOPOMOFO LETTER L
  g4 310D    -- BOPOMOFO LETTER G
  k4 310E    -- BOPOMOFO LETTER K
  h4 310F    -- BOPOMOFO LETTER H
  j4 3110    -- BOPOMOFO LETTER J
  q4 3111    -- BOPOMOFO LETTER Q
  x4 3112    -- BOPOMOFO LETTER X
  zh 3113    -- BOPOMOFO LETTER ZH
  ch 3114    -- BOPOMOFO LETTER CH
  sh 3115    -- BOPOMOFO LETTER SH
  r4 3116    -- BOPOMOFO LETTER R
  z4 3117    -- BOPOMOFO LETTER Z
  c4 3118    -- BOPOMOFO LETTER C
  s4 3119    -- BOPOMOFO LETTER S
  a4 311A    -- BOPOMOFO LETTER A
  o4 311B    -- BOPOMOFO LETTER O
  e4 311C    -- BOPOMOFO LETTER E
  ai 311E    -- BOPOMOFO LETTER AI
  ei 311F    -- BOPOMOFO LETTER EI
  au 3120    -- BOPOMOFO LETTER AU
  ou 3121    -- BOPOMOFO LETTER OU
  an 3122    -- BOPOMOFO LETTER AN
  en 3123    -- BOPOMOFO LETTER EN
  aN 3124    -- BOPOMOFO LETTER ANG
  eN 3125    -- BOPOMOFO LETTER ENG
  er 3126    -- BOPOMOFO LETTER ER
  i4 3127    -- BOPOMOFO LETTER I
  u4 3128    -- BOPOMOFO LETTER U
  iu 3129    -- BOPOMOFO LETTER IU
  v4 312A    -- BOPOMOFO LETTER V
  nG 312B    -- BOPOMOFO LETTER NG
  gn 312C    -- BOPOMOFO LETTER GN
  1c 3220    -- PARENTHESIZED IDEOGRAPH ONE
  2c 3221    -- PARENTHESIZED IDEOGRAPH TWO
  3c 3222    -- PARENTHESIZED IDEOGRAPH THREE
  4c 3223    -- PARENTHESIZED IDEOGRAPH FOUR
  5c 3224    -- PARENTHESIZED IDEOGRAPH FIVE
  6c 3225    -- PARENTHESIZED IDEOGRAPH SIX
  7c 3226    -- PARENTHESIZED IDEOGRAPH SEVEN
  8c 3227    -- PARENTHESIZED IDEOGRAPH EIGHT
  9c 3228    -- PARENTHESIZED IDEOGRAPH NINE
  ff FB00    -- LATIN SMALL LIGATURE FF
  fi FB01    -- LATIN SMALL LIGATURE FI
  fl FB02    -- LATIN SMALL LIGATURE FL
  ft FB05    -- LATIN SMALL LIGATURE LONG S T
  st FB06    -- LATIN SMALL LIGATURE ST
  |]
